import { create } from 'zustand/react'
import { persist } from 'zustand/middleware'
import type { DayExercise, CompletedSession, CompletedSet } from '@/types'
import { supabase } from '@/lib/supabase'
import { useAuthStore } from '@/store/useAuthStore'

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2)
}

export interface ActiveSet {
  reps: number | 'fallo'
  weight_kg?: number
  completed: boolean
}

export interface ActiveExercise {
  name: string
  name_es?: string
  gif_url?: string
  sets: ActiveSet[]
  skipped?: boolean
}

interface ActiveSession {
  workoutName: string
  startedAt: string
  exercises: ActiveExercise[]
}

interface SessionState {
  active: ActiveSession | null
  history: CompletedSession[]
  startSession: (workoutName: string, exercises: DayExercise[]) => Promise<void>
  toggleSet: (exerciseIndex: number, setIndex: number) => void
  updateSet: (exerciseIndex: number, setIndex: number, data: Partial<Pick<ActiveSet, 'reps' | 'weight_kg'>>) => void
  skipExercise: (exerciseIndex: number) => void
  removeSet: (exerciseIndex: number) => void
  addSet: (exerciseIndex: number) => void
  finishSession: () => void
  abandonSession: () => void
  loadFromSupabase: (userId: string) => Promise<void>
}

export const useSessionStore = create<SessionState>()(
  persist(
    (set, get) => ({
      active: null,
      history: [],

      startSession: async (workoutName, exercises) => {
        // Enrich gif_url for exercises that don't have it (e.g. generated by quiz)
        const missing = exercises.filter(ex => !ex.gif_url).map(ex => ex.name)
        const gifMap: Record<string, string> = {}
        if (missing.length > 0) {
          const { data } = await supabase
            .from('exercises')
            .select('name, gif_url')
            .in('name', missing)
          if (data) {
            for (const row of data) {
              if (row.gif_url) gifMap[row.name] = row.gif_url
            }
          }
        }
        set({
          active: {
            workoutName,
            startedAt: new Date().toISOString(),
            exercises: exercises.map(ex => ({
              name: ex.name,
              name_es: ex.name_es,
              gif_url: ex.gif_url ?? gifMap[ex.name],
              sets: ex.sets.map(s => ({
                reps: s.reps,
                weight_kg: s.weight_kg,
                completed: false,
              })),
            })),
          },
        })
      },

      toggleSet: (exerciseIndex, setIndex) => set(state => {
        if (!state.active) return state
        const exercises = state.active.exercises.map((ex, ei) => {
          if (ei !== exerciseIndex) return ex
          return {
            ...ex,
            sets: ex.sets.map((s, si) =>
              si === setIndex ? { ...s, completed: !s.completed } : s
            ),
          }
        })
        return { active: { ...state.active, exercises } }
      }),

      updateSet: (exerciseIndex, setIndex, data) => set(state => {
        if (!state.active) return state
        const exercises = state.active.exercises.map((ex, ei) => {
          if (ei !== exerciseIndex) return ex
          return {
            ...ex,
            sets: ex.sets.map((s, si) =>
              si === setIndex ? { ...s, ...data } : s
            ),
          }
        })
        return { active: { ...state.active, exercises } }
      }),

      finishSession: () => {
        const { active, history } = get()
        if (!active) return
        const durationMin = Math.round(
          (Date.now() - new Date(active.startedAt).getTime()) / 60000
        )
        const completed: CompletedSession = {
          id: generateId(),
          workoutName: active.workoutName,
          date: new Date().toISOString(),
          durationMin,
          exercises: active.exercises.map(ex => {
            const hasCompleted = ex.sets.some(s => s.completed)
            const isSkipped = ex.skipped || !hasCompleted
            return {
              name: ex.name,
              name_es: ex.name_es,
              skipped: isSkipped,
              sets: isSkipped ? [] : ex.sets
                .filter(s => s.completed)
                .map(s => ({ reps: s.reps, weight_kg: s.weight_kg } as CompletedSet)),
            }
          }),
        }
        set({ active: null, history: [completed, ...history] })

        const userId = useAuthStore.getState().user?.id
        if (userId) {
          supabase.from('session_history').insert({
            id: completed.id,
            user_id: userId,
            workout_name: completed.workoutName,
            date: completed.date,
            duration_min: completed.durationMin,
            exercises: completed.exercises,
          }).then(({ error }) => {
            if (error) console.error('Error guardando sesión:', error.message)
          })
        }
      },

      removeSet: (exerciseIndex) => set(state => {
        if (!state.active) return state
        const exercises = state.active.exercises.map((ex, ei) => {
          if (ei !== exerciseIndex || ex.sets.length <= 1) return ex
          return { ...ex, sets: ex.sets.slice(0, -1) }
        })
        return { active: { ...state.active, exercises } }
      }),

      addSet: (exerciseIndex) => set(state => {
        if (!state.active) return state
        const exercises = state.active.exercises.map((ex, ei) => {
          if (ei !== exerciseIndex) return ex
          const last = ex.sets[ex.sets.length - 1]
          return { ...ex, sets: [...ex.sets, { reps: last?.reps ?? 10, weight_kg: last?.weight_kg, completed: false }] }
        })
        return { active: { ...state.active, exercises } }
      }),

      skipExercise: (exerciseIndex) => set(state => {
        if (!state.active) return state
        const exercises = state.active.exercises.map((ex, ei) => {
          if (ei !== exerciseIndex) return ex
          return ex.skipped
            ? { ...ex, skipped: false }
            : { ...ex, skipped: true, sets: ex.sets.map(s => ({ ...s, completed: false })) }
        })
        return { active: { ...state.active, exercises } }
      }),

      abandonSession: () => set({ active: null }),

      loadFromSupabase: async (userId) => {
        const { data } = await supabase
          .from('session_history')
          .select('*')
          .eq('user_id', userId)
          .order('date', { ascending: false })
        if (data) {
          const history: CompletedSession[] = data.map(row => ({
            id: row.id,
            workoutName: row.workout_name,
            date: row.date,
            durationMin: row.duration_min,
            exercises: row.exercises,
          }))
          // Preserve active session — don't overwrite it with Supabase data
          set(state => ({ history, active: state.active }))
        }
      },
    }),
    { name: 'session-store', partialize: (state) => ({ history: state.history, active: state.active }) }
  )
)
